apiVersion: v1
kind: Service
metadata:
  name: security
  namespace: nexusgate
  labels:
    app.kubernetes.io/name: security
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: nexusgate
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: security
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
