apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexusgate
  namespace: nexusgate
  annotations:
    # Workload Identity: bind this K8s SA to the GCP SA created by Terraform
    # Replace PROJECT_ID with your actual GCP project ID
    iam.gke.io/gcp-service-account: nexusgate-workload@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: nexusgate
